/**
 * Business-mode copy, PL/EN. Follows `material-copy.ts`'s pattern: one locale
 * object per language, selected by prefix, so every user-facing string stays
 * translatable and none is hard-coded in a component.
 *
 * Wording rules this file exists to hold:
 *
 * - **"w asortymencie", never "dostępny na magazynie"** — V54 knows what a
 *   wholesaler *sells*, not what is physically in stock (§47);
 * - **"preferowany"** is labelled a commercial choice, never a technical
 *   recommendation (§45);
 * - a missing organization price says so; it never silently becomes a
 *   catalogue price (§41);
 * - a product outside the assortment is a *commercial* state — the roof stays
 *   technically valid and the copy must say that plainly (§17).
 */

const pl = {
  mode: 'Tryb',
  standard: 'Standardowy',
  business: 'Biznesowy (hurtownia)',
  organization: 'Hurtownia',
  chooseOrganization: 'Wybierz hurtownię',
  priceListLabel: 'Cennik',
  salesDesk: 'Pulpit sprzedaży',
  salesDeskIntro:
    'Rozpocznij wycenę dla klienta albo wróć do ostatniego projektu.',
  newEstimation: 'Nowa wycena',
  newRoofEstimation: 'Nowa wycena dachu',
  newRoofEstimationHint:
    'Klient i inwestycja najpierw, projekt techniczny w następnym kroku.',
  customerAndProject: 'Klient i inwestycja',
  customerName: 'Klient — nazwa lub firma',
  customerPlaceholder: 'Jan Kowalski / Firma Kowalski',
  investmentName: 'Nazwa inwestycji',
  investmentPlaceholder: 'Dom jednorodzinny Kowalski',
  locationOptional: 'Lokalizacja (opcjonalnie)',
  locationPlaceholder: 'Kraków',
  customerDetailsOptional: 'Dane klienta do oferty (opcjonalnie)',
  companyName: 'Nazwa firmy',
  taxId: 'NIP',
  email: 'E-mail',
  phone: 'Telefon',
  address: 'Adres',
  createAndOpenRoof: 'Utwórz i przejdź do dachu',
  creatingEstimation: 'Tworzenie wyceny…',
  estimationCreateFailed: 'Nie udało się utworzyć wyceny.',
  recent: 'Ostatnie projekty / wyceny',
  noRecentProjects: 'Nie ma jeszcze wcześniejszych projektów.',
  openAssortment: 'Asortyment',
  priceListImport: 'Cennik / Import',
  organizationOnlyPricing:
    'Do wycen używany jest wyłącznie aktualny cennik hurtowni. Braki cen pozostają widoczne.',
  continueEstimation: 'Kontynuuj wycenę',
  openTechnicalProject: 'Przejdź do otwartego projektu',
  estimation: 'Wycena',
  customer: 'Klient',
  companyAssortment: 'Asortyment firmy',
  wholeCatalog: 'Cały katalog techniczny',
  browseCatalog: 'Przeglądaj cały katalog techniczny',
  searchAssortment: 'Szukaj w asortymencie firmy',
  clearSearch: 'Wyczyść wyszukiwanie',
  wholesalerCode: 'Kod hurtowni',
  preferred: 'Preferowany',
  preferredHint:
    'Wybór handlowy hurtowni — nie jest to rekomendacja techniczna.',
  priceAvailable: 'Cena: dostępna',
  priceMissing: 'Cena: brak',
  organizationPrice: (amount: string, unit: string) =>
    `Cena: ${amount} netto / ${unit}`,
  saleUnit: {
    piece: 'szt.',
    pack: 'opak.',
    pallet: 'paleta',
    roll: 'rolka',
    m: 'm',
    m2: 'm²',
    m3: 'm³',
    kg: 'kg',
    hour: 'godz.',
    flat: 'kpl.',
  } as Record<string, string>,
  use: 'Użyj produktu',
  detailsAndChoose: 'Sprawdź i wybierz',
  productDetails: 'Dane produktu',
  dimensions: 'Wymiary',
  effectiveCoverWidth: 'Efektywna szerokość krycia',
  gaugeRange: 'Zakres łat',
  technicalDataComplete: 'Dane techniczne kompletne',
  backToProducts: 'Wróć do produktów',
  applying: 'Pobieranie rewizji…',
  applyFailed: 'Nie udało się pobrać danych technicznych produktu.',
  loading: 'Ładowanie asortymentu…',
  unavailable: 'Dane firmy są chwilowo niedostępne.',
  noProductsOfKind: 'Hurtownia nie ma w asortymencie produktów tego typu.',
  noSearchResults: 'Brak pozycji spełniających kryteria.',
  loadMore: 'Załaduj więcej',
  loadingMore: 'Ładowanie…',
  productCount: (count: number) =>
    `${count} ${count === 1 ? 'produkt' : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 10 || count % 100 >= 20) ? 'produkty' : 'produktów'}`,

  outsideAssortment: 'Brak w asortymencie',
  outsideAssortmentDetail: (name: string) =>
    `Produkt poza aktywnym asortymentem: ${name}.`,
  outsideAssortmentTechnical:
    'Obliczenia techniczne pozostają ważne — zmienia się tylko stan handlowy.',
  findReplacement: 'Znajdź zamiennik w asortymencie',
  keepTechnicalProduct: 'Zostaw produkt techniczny',
  noWholesalePrice: 'Brak ceny w cenniku hurtowni',
  cataloguePriceUsed: 'Cena katalogowa (spoza hurtowni)',
  pricePolicy: 'Źródło ceny',
  policyOrganizationOnly: 'Tylko cennik hurtowni',
  policyWithFallback: 'Cennik hurtowni, w razie braku katalogowa',

  admin: 'Administracja',
  adminAssortment: 'Asortyment',
  adminImport: 'Importuj CSV',
  manualEntry: 'Dodaj produkt ręcznie',
  addProduct: 'Dodaj produkt',
  cancel: 'Anuluj',
  optionalPrice: 'Cena (opcjonalnie)',
  priceEditor: 'Nowa wersja ceny',
  netPrice: 'Cena netto',
  saleUnitLabel: 'Jednostka sprzedaży',
  vatRate: 'VAT (%)',
  validFrom: 'Obowiązuje od',
  saveNewPrice: 'Zapisz nową cenę',
  priceHistory: 'Historia cen',
  noPriceHistory: 'Brak wcześniejszych cen.',
  invalidManualEntry: 'Sprawdź cenę, VAT i powiązanie produktu.',
  adminDashboard: 'Panel hurtowni',
  adminDisabled:
    'Edycja asortymentu jest wyłączona na tym serwerze. Administracja działa wyłącznie lokalnie (BUSINESS_ADMIN_DEV_MODE).',
  adminReadOnly: 'Tylko podgląd',
  countAssortment: 'Asortyment',
  countMatched: 'Powiązane',
  countUnmatched: 'Niepowiązane',
  countWithoutPrice: 'Bez ceny',
  countWithoutVat: 'Bez VAT',
  catalogData: 'Dane katalogowe',
  databaseConnected: 'Połączono',
  databaseUnavailable: 'Dane niedostępne',
  catalogEmpty: 'Katalog nie został jeszcze zasilony.',
  initializationGuide: 'Instrukcja inicjalizacji',
  dataQuality: 'Jakość danych',
  qualityUnmatched: 'Produkty bez dopasowania technicznego',
  qualityMatchedWithoutPrice: 'Powiązane bez ceny',
  qualityWithoutSku: 'Warianty bez kodu hurtowni',
  qualityInactive: 'Nieaktywne',
  qualityUnavailableToCompany: 'Produkty techniczne poza asortymentem firmy',
  technicalProducts: 'Produkty techniczne',
  technicalRevisions: 'Rewizje',
  commercialVariants: 'Warianty',
  priceEntries: 'Pozycje cenowe firmy',
  lastImport: 'Ostatni import',
  countInactive: 'Nieaktywne',
  filterAll: 'Wszystkie',
  filterActive: 'Aktywne',
  filterUnmatched: 'Niepowiązane',
  filterWithoutPrice: 'Bez ceny',
  filterWithoutVat: 'Bez VAT',
  bulkSetVat: 'Zastosuj VAT do zaznaczonych',
  filterInactive: 'Nieaktywne',
  filterPreferred: 'Preferowane',
  selectedCount: (count: number) => `Zaznaczono: ${count}`,
  selectAllVisible: 'Zaznacz widoczne',
  selectRow: 'Zaznacz produkt',
  bulkActivate: 'Aktywuj',
  bulkDeactivate: 'Dezaktywuj',
  bulkPrefer: 'Oznacz jako preferowane',
  bulkUnprefer: 'Usuń preferowanie',
  columnCode: 'Kod',
  columnName: 'Nazwa hurtowni',
  columnMatch: 'Producent / dopasowanie RoofCalc',
  columnStatus: 'Status',
  columnPrice: 'Cena',
  columnActive: 'Aktywny',
  stateMatched: 'Powiązany',
  stateUnmatched: 'NIEPOWIĄZANY',
  stateInactive: 'Nieaktywny',
  detailTitle: 'Produkt hurtowni',
  internalSku: 'Kod hurtowni (SKU)',
  importedName: 'Nazwa z importu',
  ean: 'EAN',
  matchedProduct: 'Dopasowany produkt techniczny',
  commercialVariant: 'Wariant handlowy',
  link: 'Połącz z katalogiem RoofCalc',
  linkConfirm: 'Połącz',
  unlink: 'Usuń powiązanie',
  searchCatalog: 'Szukaj w katalogu RoofCalc',
  unmatchedWarning:
    'Pozycja niepowiązana nie może być użyta jako materiał techniczny — RoofCalc nie zna jej wymiarów ani zasad montażu.',
  noVariantsToLink:
    'Ten produkt nie ma jeszcze wariantów handlowych w katalogu — nie można go powiązać.',
  actionFailed: 'Operacja nie powiodła się.',
  errorCode: {
    'duplicate-active-variant':
      'Ten wariant handlowy jest już powiązany z inną aktywną pozycją asortymentu.',
    'duplicate-external-key': 'Pozycja z tym kodem hurtowni już istnieje.',
    'commercial-variant-not-found':
      'Tego wariantu nie ma w katalogu technicznym RoofCalc.',
    'assortment-item-not-found': 'Nie znaleziono tej pozycji asortymentu.',
    'organization-not-found': 'Nie znaleziono tej hurtowni.',
    'business-invalid-request': 'Nieprawidłowe dane żądania.',
    'business-unavailable': 'Dane firmy są chwilowo niedostępne.',
  } as Record<string, string>,
  markPreferred: 'Oznacz jako preferowany',
  unmarkPreferred: 'Usuń oznaczenie preferowany',
  activate: 'Aktywuj',
  deactivate: 'Dezaktywuj',
  skip: 'Pomiń',
  back: 'Wróć do listy',

  importTitle: 'Import asortymentu (CSV)',
  importStepFile: '1. Wybierz plik CSV',
  importStepMapping: '2. Przypisz kolumny',
  importStepPreview: '3. Podgląd',
  importStepApply: '4. Zapisz',
  importChooseFile: 'Wybierz plik CSV',
  importRows: (count: number) => `${count} wierszy`,
  importMatched: 'dopasowane',
  importNeedsReview: 'wymagają sprawdzenia',
  importNoMatch: 'bez odpowiednika',
  importInvalidPrice: 'błędne ceny',
  importShowProblems: 'Pokaż problemy',
  importHideProblems: 'Ukryj problemy',
  importRun: 'Importuj',
  importDryRun: 'Sprawdź (bez zapisu)',
  importApplied: 'Import zapisany.',
  importFailed: 'Import nie powiódł się.',
  importCreate: 'nowe',
  importUpdate: 'aktualizacja',
  importUnchanged: 'bez zmian',
  importSkip: 'pominięte',
  fieldExternalKey: 'Kod hurtowni',
  fieldSourceName: 'Nazwa',
  fieldEan: 'EAN',
  fieldManufacturer: 'Producent',
  fieldNetAmount: 'Cena netto',
  fieldGrossAmount: 'Cena brutto',
  fieldVatRate: 'Stawka VAT',
  fieldSaleUnit: 'Jednostka sprzedaży',
  fieldActive: 'Aktywny',
  mappingIgnore: '— pomiń —',
  mappingRequired: 'Kod hurtowni i Nazwa są wymagane.',
  issue: {
    'missing-external-key': 'Brak kodu hurtowni',
    'missing-name': 'Brak nazwy',
    'invalid-price': 'Nieczytelna cena',
    'invalid-vat-rate': 'Nieprawidłowy VAT',
    'gross-price-without-vat-rate': 'Brak stawki VAT / ceny netto',
    'invalid-sale-unit': 'Nieznana jednostka sprzedaży',
    'duplicate-external-key': 'Powtórzony kod hurtowni',
  } as Record<string, string>,
  matchState: {
    matched: 'DOPASOWANO',
    suggested: 'SUGESTIA',
    ambiguous: 'NIEJEDNOZNACZNE',
    'no-match': 'BRAK DOPASOWANIA',
  } as Record<string, string>,
};

type Copy = typeof pl;

const en: Copy = {
  mode: 'Mode',
  standard: 'Standard',
  business: 'Business (wholesaler)',
  organization: 'Wholesaler',
  chooseOrganization: 'Choose a wholesaler',
  priceListLabel: 'Price list',
  salesDesk: 'Sales desk',
  salesDeskIntro: 'Start a customer estimate or return to a recent project.',
  newEstimation: 'New estimate',
  newRoofEstimation: 'New roof estimate',
  newRoofEstimationHint:
    'Customer and job first, technical roof in the next step.',
  customerAndProject: 'Customer and project',
  customerName: 'Customer — name or company',
  customerPlaceholder: 'John Smith / Smith Ltd',
  investmentName: 'Project name',
  investmentPlaceholder: 'Smith family house',
  locationOptional: 'Location (optional)',
  locationPlaceholder: 'Kraków',
  customerDetailsOptional: 'Customer details for the quote (optional)',
  companyName: 'Company name',
  taxId: 'Tax ID',
  email: 'Email',
  phone: 'Phone',
  address: 'Address',
  createAndOpenRoof: 'Create and continue to roof',
  creatingEstimation: 'Creating estimate…',
  estimationCreateFailed: 'The estimate could not be created.',
  recent: 'Recent projects / estimates',
  noRecentProjects: 'There are no earlier projects yet.',
  openAssortment: 'Assortment',
  priceListImport: 'Price list / Import',
  organizationOnlyPricing:
    'Only the current wholesaler price list is used in estimates. Missing prices remain visible.',
  continueEstimation: 'Continue estimate',
  openTechnicalProject: 'Open current technical project',
  estimation: 'Estimate',
  customer: 'Customer',
  companyAssortment: 'Company assortment',
  wholeCatalog: 'Full technical catalogue',
  browseCatalog: 'Browse the full technical catalogue',
  searchAssortment: 'Search the company assortment',
  clearSearch: 'Clear search',
  wholesalerCode: 'Wholesaler code',
  preferred: 'Preferred',
  preferredHint:
    "The wholesaler's commercial preference — not a technical recommendation.",
  priceAvailable: 'Price: available',
  priceMissing: 'Price: missing',
  organizationPrice: (amount: string, unit: string) =>
    `Price: ${amount} net / ${unit}`,
  saleUnit: {
    piece: 'pc',
    pack: 'pack',
    pallet: 'pallet',
    roll: 'roll',
    m: 'm',
    m2: 'm²',
    m3: 'm³',
    kg: 'kg',
    hour: 'hour',
    flat: 'set',
  },
  use: 'Use product',
  detailsAndChoose: 'Review and choose',
  productDetails: 'Product details',
  dimensions: 'Dimensions',
  effectiveCoverWidth: 'Effective cover width',
  gaugeRange: 'Batten gauge range',
  technicalDataComplete: 'Technical data complete',
  backToProducts: 'Back to products',
  applying: 'Fetching revision…',
  applyFailed: 'Could not fetch the technical data for this product.',
  loading: 'Loading assortment…',
  unavailable: 'Company data is temporarily unavailable.',
  noProductsOfKind: 'The wholesaler carries no products of this type.',
  noSearchResults: 'No rows match these criteria.',
  loadMore: 'Load more',
  loadingMore: 'Loading…',
  productCount: (count: number) =>
    `${count} ${count === 1 ? 'product' : 'products'}`,

  outsideAssortment: 'Not in assortment',
  outsideAssortmentDetail: (name: string) =>
    `Product outside the active assortment: ${name}.`,
  outsideAssortmentTechnical:
    'The technical calculation stays valid — only the commercial state changes.',
  findReplacement: 'Find a replacement in the assortment',
  keepTechnicalProduct: 'Keep the technical product',
  noWholesalePrice: "No price in the wholesaler's price list",
  cataloguePriceUsed: 'Catalogue price (not from the wholesaler)',
  pricePolicy: 'Price source',
  policyOrganizationOnly: 'Wholesaler price list only',
  policyWithFallback: 'Wholesaler price list, catalogue as fallback',

  admin: 'Administration',
  adminAssortment: 'Assortment',
  adminImport: 'Import CSV',
  manualEntry: 'Add product manually',
  addProduct: 'Add product',
  cancel: 'Cancel',
  optionalPrice: 'Price (optional)',
  priceEditor: 'New price version',
  netPrice: 'Net price',
  saleUnitLabel: 'Sale unit',
  vatRate: 'VAT (%)',
  validFrom: 'Valid from',
  saveNewPrice: 'Save new price',
  priceHistory: 'Price history',
  noPriceHistory: 'No earlier prices.',
  invalidManualEntry: 'Check the price, VAT, and product link.',
  adminDashboard: 'Wholesaler dashboard',
  adminDisabled:
    'Assortment editing is disabled on this server. Administration runs locally only (BUSINESS_ADMIN_DEV_MODE).',
  adminReadOnly: 'Read only',
  countAssortment: 'Assortment',
  countMatched: 'Matched',
  countUnmatched: 'Unmatched',
  countWithoutPrice: 'Without price',
  countWithoutVat: 'Without VAT',
  catalogData: 'Catalogue data',
  databaseConnected: 'Connected',
  databaseUnavailable: 'Data unavailable',
  catalogEmpty: 'The catalogue has not been initialized yet.',
  initializationGuide: 'Initialization guide',
  dataQuality: 'Data quality',
  qualityUnmatched: 'Products without a technical match',
  qualityMatchedWithoutPrice: 'Matched without price',
  qualityWithoutSku: 'Variants without a company SKU',
  qualityInactive: 'Inactive',
  qualityUnavailableToCompany: 'Technical products outside company assortment',
  technicalProducts: 'Technical products',
  technicalRevisions: 'Revisions',
  commercialVariants: 'Variants',
  priceEntries: 'Company price entries',
  lastImport: 'Last import',
  countInactive: 'Inactive',
  filterAll: 'All',
  filterActive: 'Active',
  filterUnmatched: 'Unmatched',
  filterWithoutPrice: 'Without price',
  filterWithoutVat: 'Without VAT',
  bulkSetVat: 'Apply VAT to selected',
  filterInactive: 'Inactive',
  filterPreferred: 'Preferred',
  selectedCount: (count: number) => `Selected: ${count}`,
  selectAllVisible: 'Select visible rows',
  selectRow: 'Select product',
  bulkActivate: 'Activate',
  bulkDeactivate: 'Deactivate',
  bulkPrefer: 'Mark preferred',
  bulkUnprefer: 'Remove preferred',
  columnCode: 'Code',
  columnName: 'Wholesaler name',
  columnMatch: 'Manufacturer / RoofCalc match',
  columnStatus: 'Status',
  columnPrice: 'Price',
  columnActive: 'Active',
  stateMatched: 'Matched',
  stateUnmatched: 'UNMATCHED',
  stateInactive: 'Inactive',
  detailTitle: 'Wholesaler product',
  internalSku: 'Internal SKU',
  importedName: 'Imported name',
  ean: 'EAN',
  matchedProduct: 'Matched technical product',
  commercialVariant: 'Commercial variant',
  link: 'Link to the RoofCalc catalogue',
  linkConfirm: 'Link',
  unlink: 'Remove link',
  searchCatalog: 'Search the RoofCalc catalogue',
  unmatchedWarning:
    'An unmatched row cannot be used as technical material — RoofCalc knows none of its dimensions or installation rules.',
  noVariantsToLink:
    'This product has no commercial variants in the catalogue yet, so it cannot be linked.',
  actionFailed: 'The action failed.',
  errorCode: {
    'duplicate-active-variant':
      'This commercial variant is already linked to another active assortment row.',
    'duplicate-external-key':
      'An assortment row with this wholesaler code already exists.',
    'commercial-variant-not-found':
      'That variant does not exist in the RoofCalc technical catalogue.',
    'assortment-item-not-found': 'That assortment row was not found.',
    'organization-not-found': 'That wholesaler was not found.',
    'business-invalid-request': 'The request data was not valid.',
    'business-unavailable': 'Company data is temporarily unavailable.',
  },
  markPreferred: 'Mark as preferred',
  unmarkPreferred: 'Remove preferred mark',
  activate: 'Activate',
  deactivate: 'Deactivate',
  skip: 'Skip',
  back: 'Back to the list',

  importTitle: 'Assortment import (CSV)',
  importStepFile: '1. Choose a CSV file',
  importStepMapping: '2. Map the columns',
  importStepPreview: '3. Preview',
  importStepApply: '4. Apply',
  importChooseFile: 'Choose a CSV file',
  importRows: (count: number) => `${count} rows`,
  importMatched: 'matched',
  importNeedsReview: 'need review',
  importNoMatch: 'without a counterpart',
  importInvalidPrice: 'price problems',
  importShowProblems: 'Show problems',
  importHideProblems: 'Hide problems',
  importRun: 'Import',
  importDryRun: 'Check (no write)',
  importApplied: 'Import applied.',
  importFailed: 'The import failed.',
  importCreate: 'new',
  importUpdate: 'updated',
  importUnchanged: 'unchanged',
  importSkip: 'skipped',
  fieldExternalKey: 'Wholesaler code',
  fieldSourceName: 'Name',
  fieldEan: 'EAN',
  fieldManufacturer: 'Manufacturer',
  fieldNetAmount: 'Net price',
  fieldGrossAmount: 'Gross price',
  fieldVatRate: 'VAT rate',
  fieldSaleUnit: 'Sale unit',
  fieldActive: 'Active',
  mappingIgnore: '— skip —',
  mappingRequired: 'Wholesaler code and Name are required.',
  issue: {
    'missing-external-key': 'Missing wholesaler code',
    'missing-name': 'Missing name',
    'invalid-price': 'Unreadable price',
    'invalid-vat-rate': 'Invalid VAT rate',
    'gross-price-without-vat-rate': 'No VAT rate / net price',
    'invalid-sale-unit': 'Unknown sale unit',
    'duplicate-external-key': 'Duplicate wholesaler code',
  },
  matchState: {
    matched: 'MATCHED',
    suggested: 'SUGGESTION',
    ambiguous: 'AMBIGUOUS',
    'no-match': 'NO MATCH',
  },
};

export function businessCopy(locale: string): Copy {
  return locale.startsWith('pl') ? pl : en;
}

export type BusinessCopy = Copy;
