const pl = {
  title: 'Plan materiałów',
  timber: 'Drewno konstrukcyjne',
  layers: 'Warstwy',
  covering: 'Pokrycie',
  other: 'Pozostałe',
  k1: 'K1 · krokwie',
  battens: 'Łaty',
  counterBattens: 'Kontrłaty',
  membrane: 'Membrana',
  tile: 'Dachówka',
  timberEvidence: 'Drewno · zestawienie geometryczne',
  blankLength: 'Długość blanku',
  consumption: 'Deklarowane zużycie producenta',
  netArea: 'Powierzchnia netto',
  grossArea: 'Powierzchnia z zakładami',
  rollCount: 'Liczba rolek (bez ponownego użycia)',
  procurement: 'PLAN ZAKUPU',
  fabrication: 'WYMAGANIE WYKONAWCZE',
  geometry: 'GEOMETRIA',
  manufacturer: 'SZACUNEK PRODUCENTA',
  partial: 'CZĘŚCIOWE',
  catalogue: 'KATALOG',
  manual: 'CENA RĘCZNA',
  noPrice: 'Brak ceny w cenniku',
  selectPrice: 'Wybierz źródło ceny',
  manualPrice: 'Cena ręczna netto',
  price: 'Cena netto',
  value: 'Wartość netto',
  net: 'netto',
  gross: 'źródło brutto',
  verify: 'Zweryfikuj cenę przed zakupem',
  commercial: 'Wybrany materiał handlowy',
  online: 'Katalog online',
  offline: 'Katalog niedostępny — obliczenia lokalne działają',
  loading: 'Sprawdzanie katalogu…',
  cutting: 'Rozkrój K1',
  technical: 'Zestawienie techniczne',
  chooseTimber: 'Dobierz tarcicę w rozkroju K1',
  chooseMembrane: 'Zmień produkt',
  parameters: 'Parametry / wpisz ręcznie',
  chooseCovering: 'Wybierz wariant w Pokryciu',
  details: 'Szczegóły i podstawa ilości',
  add: 'Dodaj do kosztorysu',
  update: 'Aktualizuj kosztorys',
  keep: 'Zachowaj obecną',
  review: 'Proponowana aktualizacja',
  manualOwned:
    'Ilość ręczna pozostaje bez zmian. Aktualizacja ceny wymaga akceptacji.',
  rangeNote: 'Szacunek — nie ilość zakupowa. Bez automatycznego zapasu.',
  rangeCost: 'Zakres kosztu',
  rangeAction: 'Ustal ilość w kosztorysie',
  count: 'Pozycje',
  purchaseCount: 'Plan zakupowy',
  estimates: 'Szacunki',
  needsData: 'Wymagają danych',
  known: 'Wartość znanych cen (netto)',
  incomplete: 'Wartość częściowa — pomija niepełne pozycje i brakujące ceny.',
  csv: 'Pobierz listę CSV',
  export: 'Lista materiałów / druk',
  empty:
    'Brak materiałów do pokazania. Uzupełnij konstrukcję, warstwy lub pokrycie.',
  'k1-needs-cutting':
    'Uruchom pełny rozkrój, aby dobrać długości handlowe. To wymaganie wykonawcze, nie plan zakupu.',
  'layer-not-resolved':
    'Nie określono ilości. Sprawdź parametry i ograniczenia w Warstwach.',
  'k1-execution-unresolved':
    'Geometria osi nie określa blanków. Przygotowanie K1 jest nierozwiązane w tej konfiguracji.',
  'no-allowance-no-stock-length': 'Bez zapasu i rozkroju handlowego.',
  'partial-counter-battens':
    'Częściowo policzone: osie K1/J1 i przerwy przy otworach; detal przy narożnych H1 pozostaje nierozwiązany.',
  'gross-area-no-roll-reuse':
    'Nie uwzględniono ponownego wykorzystania odcinków rolek.',
  'hip-course-width-approximated':
    'Na dachu kopertowym szerokość pasów przybliżono szerokością okapu.',
  'openings-not-subtracted': 'Otwory nie są odliczane w układzie membrany.',
  'net-area-no-overlap-no-rolls':
    'Powierzchnia geometryczna netto, bez zakładów i liczby rolek. Wybierz produkt rolkowy.',
  'declared-consumption-not-a-resolved-purchase-count':
    'Szacunek według zużycia deklarowanego przez producenta; nie jest ilością zakupową.',
  'covering-not-a-purchase-count':
    'Pozycje krycia i przebiegi geometryczne nie określają ilości do zakupu.',
};
const en: typeof pl = {
  title: 'Material plan',
  timber: 'Structural timber',
  layers: 'Layers',
  covering: 'Covering',
  other: 'Other',
  k1: 'K1 · rafters',
  battens: 'Battens',
  counterBattens: 'Counter battens',
  membrane: 'Membrane',
  tile: 'Roof tile',
  timberEvidence: 'Timber · geometric schedule',
  blankLength: 'Blank length',
  consumption: 'Declared manufacturer consumption',
  netArea: 'Net area',
  grossArea: 'Area including overlaps',
  rollCount: 'Roll count (without reuse)',
  procurement: 'PURCHASE PLAN',
  fabrication: 'FABRICATION REQUIREMENT',
  geometry: 'GEOMETRY',
  manufacturer: 'MANUFACTURER ESTIMATE',
  partial: 'PARTIAL',
  catalogue: 'CATALOGUE',
  manual: 'MANUAL PRICE',
  noPrice: 'No price in list',
  selectPrice: 'Select price source',
  manualPrice: 'Manual net unit price',
  price: 'Net unit price',
  value: 'Net value',
  net: 'net',
  gross: 'source gross',
  verify: 'Verify price before purchase',
  commercial: 'Selected commercial material',
  online: 'Catalogue online',
  offline: 'Catalogue unavailable — local calculations work',
  loading: 'Checking catalogue…',
  cutting: 'K1 cutting plan',
  technical: 'Technical schedule',
  chooseTimber: 'Choose timber in K1 cutting plan',
  chooseMembrane: 'Change product',
  parameters: 'Parameters / manual entry',
  chooseCovering: 'Choose variant in Covering',
  details: 'Details and quantity basis',
  add: 'Add to estimate',
  update: 'Update estimate',
  keep: 'Keep current',
  review: 'Proposed update',
  manualOwned:
    'Manual quantity remains unchanged. Accept price updates explicitly.',
  rangeNote: 'Estimate — not a purchase quantity. No automatic allowance.',
  rangeCost: 'Cost range',
  rangeAction: 'Set quantity in estimate',
  count: 'Rows',
  purchaseCount: 'Purchase plan',
  estimates: 'Estimates',
  needsData: 'Need data',
  known: 'Known prices value (net)',
  incomplete: 'Partial value — excludes incomplete rows and missing prices.',
  csv: 'Download material CSV',
  export: 'Material list / print',
  empty: 'No materials yet. Complete structure, layers or covering.',
  'k1-needs-cutting':
    'Run a complete cutting plan to choose commercial lengths. This is a fabrication requirement.',
  'layer-not-resolved':
    'Quantity is unresolved. Review parameters and limitations in Layers.',
  'k1-execution-unresolved':
    'Axis geometry does not define blanks. K1 fabrication is unresolved for this configuration.',
  'no-allowance-no-stock-length': 'Without allowances or commercial cutting.',
  'partial-counter-battens':
    'Partial: K1/J1 axes and opening interruptions; H1 boundary detail remains unresolved.',
  'gross-area-no-roll-reuse': 'No reuse of roll offcuts.',
  'hip-course-width-approximated': 'Hip courses use approximated eave width.',
  'openings-not-subtracted':
    'Openings are not subtracted from membrane layout.',
  'net-area-no-overlap-no-rolls':
    'Net geometric area without overlaps or rolls. Select a roll product.',
  'declared-consumption-not-a-resolved-purchase-count':
    'Manufacturer consumption estimate; not a purchase quantity.',
  'covering-not-a-purchase-count':
    'Coverage positions and geometric runs do not define purchase quantities.',
};
export function materialCopy(locale: string) {
  return locale.startsWith('pl') ? pl : en;
}
export function materialText(locale: string, key: string) {
  const copy = materialCopy(locale);
  return copy[key as keyof typeof copy] ?? key;
}
