const pl = {
  title: 'Plan materiałów',
  timber: 'Drewno konstrukcyjne',
  layers: 'Warstwy',
  covering: 'Pokrycie',
  other: 'Pozostałe',
  k1: 'K1 · krokwie',
  battens: 'Łaty',
  counterBattens: 'Kontrłaty',
  membrane: 'Membrana',
  tile: 'Dachówka',
  timberEvidence: 'Drewno · zestawienie geometryczne',
  blankLength: 'Długość blanku',
  consumption: 'Deklarowane zużycie producenta',
  netArea: 'Powierzchnia netto',
  grossArea: 'Z uwzględnieniem zakładów',
  rollCount: 'Plan rolek (wg obecnego układu)',
  overlapArea: 'Zakłady między pasami',
  endOverlapArea: 'Zakłady na łączeniach rolek',
  ridgeOverrunArea: 'Nadmiar ostatniego pasa przy kalenicy',
  simplificationArea: 'Uproszczenia układu (szerokość okapu, otwory)',
  courseCount: 'Pasy membrany',
  course: 'pas.',
  roll: 'rol.',
  membraneRollPlan: 'PLAN KONSERWATYWNY',
  membraneNetOnly: 'TYLKO NETTO',
  membraneRollPlanHelp:
    'Pełne pasy od okapu do kalenicy z zakładem produktu. Rolki liczone bez ponownego układania pozostałych odcinków — to górne oszacowanie, nie dokładny plan zakupu.',
  membraneNetOnlyHelp:
    'Tylko geometria dachu. Wybierz produkt rolkowy, aby policzyć zakłady, pasy i rolki.',
  netHero: 'Powierzchnia netto',
  grossHero: 'Z uwzględnieniem zakładów',
  rollsHero: 'Plan wg obecnego układu',
  rollSize: 'Rolka',
  rollWidth: 'Szerokość rolki',
  rollLength: 'Długość rolki',
  overlapUsed: 'Zakład (użyty)',
  manualData: 'RĘCZNIE',
  manualDataHelp:
    'Dane techniczne wpisane przez użytkownika — nie pochodzą z rewizji katalogu.',
  catalogRevision: 'rewizja',
  noProduct: 'Nie wybrano produktu',
  limitations: 'Czego RoofCalc jeszcze nie modeluje',
  whyMore: 'Dlaczego więcej niż netto?',
  retry: 'Spróbuj ponownie',
  geometryCount: 'Geometria',
  procurement: 'PLAN ZAKUPU',
  fabrication: 'WYMAGANIE WYKONAWCZE',
  geometry: 'GEOMETRIA',
  manufacturer: 'SZACUNEK PRODUCENTA',
  partial: 'CZĘŚCIOWE',
  catalogue: 'KATALOG',
  manual: 'CENA RĘCZNA',
  noPrice: 'Brak ceny w cenniku',
  selectPrice: 'Wybierz źródło ceny',
  manualPrice: 'Cena ręczna netto',
  price: 'Cena netto',
  value: 'Wartość netto',
  net: 'netto',
  gross: 'źródło brutto',
  verify: 'Zweryfikuj cenę przed zakupem',
  commercial: 'Wybrany materiał handlowy',
  online: 'Katalog dostępny',
  offline: 'Katalog niedostępny — możesz pracować ręcznie',
  loading: 'Sprawdzanie katalogu…',
  cutting: 'Rozkrój K1',
  technical: 'Zestawienie techniczne',
  chooseTimber: 'Dobierz tarcicę w rozkroju K1',
  chooseMembrane: 'Zmień produkt',
  parameters: 'Parametry / wpisz ręcznie',
  chooseCovering: 'Wybierz wariant w Pokryciu',
  details: 'Szczegóły i podstawa ilości',
  add: 'Dodaj do kosztorysu',
  update: 'Aktualizuj kosztorys',
  keep: 'Zachowaj obecną',
  review: 'Proponowana aktualizacja',
  manualOwned:
    'Ilość ręczna pozostaje bez zmian. Aktualizacja ceny wymaga akceptacji.',
  rangeNote: 'Szacunek — nie ilość zakupowa. Bez automatycznego zapasu.',
  rangeCost: 'Zakres kosztu',
  rangeAction: 'Ustal ilość w kosztorysie',
  count: 'Pozycje',
  purchaseCount: 'Plan zakupowy',
  estimates: 'Szacunki',
  needsData: 'Wymagają danych',
  known: 'Wartość znanych cen (netto)',
  incomplete: 'Wartość częściowa — pomija niepełne pozycje i brakujące ceny.',
  csv: 'Pobierz listę CSV',
  export: 'Lista materiałów / druk',
  empty:
    'Brak materiałów do pokazania. Uzupełnij konstrukcję, warstwy lub pokrycie.',
  'k1-needs-cutting':
    'Uruchom pełny rozkrój, aby dobrać długości handlowe. To wymaganie wykonawcze, nie plan zakupu.',
  'layer-not-resolved':
    'Nie określono ilości. Sprawdź parametry i ograniczenia w Warstwach.',
  'k1-execution-unresolved':
    'Geometria osi nie określa blanków. Przygotowanie K1 jest nierozwiązane w tej konfiguracji.',
  'no-allowance-no-stock-length': 'Bez zapasu i rozkroju handlowego.',
  'partial-counter-battens':
    'Częściowo policzone: osie K1/J1 i przerwy przy otworach; detal przy narożnych H1 pozostaje nierozwiązany.',
  'batten-gauge-unverified':
    'Rozstaw ręczny, niezweryfikowany z pokryciem — długość geometryczna wstępna.',
  'batten-gauge-incompatible':
    'Rozstaw łat jest niezgodny z pokryciem — długość geometryczna do poprawy.',
  'gross-area-no-roll-reuse':
    'Pozostałe odcinki rolki nie są ponownie układane między pasami.',
  'hip-course-width-approximated':
    'Połać kopertowa jest obecnie liczona konserwatywnie: każdy pas ma szerokość okapu.',
  'openings-not-subtracted':
    'Otwory dachowe nie pomniejszają jeszcze zapotrzebowania na membranę.',
  'membrane-sold-per-roll':
    'Produkt sprzedawany na rolki, ale kosztorys nie obsługuje jeszcze ceny za rolkę — koszt liczony za m² z zakładami.',
  'net-area-no-overlap-no-rolls':
    'Powierzchnia geometryczna netto, bez zakładów i liczby rolek. Wybierz produkt rolkowy.',
  'declared-consumption-not-a-resolved-purchase-count':
    'Szacunek według zużycia deklarowanego przez producenta; nie jest ilością zakupową.',
  'covering-not-a-purchase-count':
    'Pozycje krycia i przebiegi geometryczne nie określają ilości do zakupu.',
};
const en: typeof pl = {
  title: 'Material plan',
  timber: 'Structural timber',
  layers: 'Layers',
  covering: 'Covering',
  other: 'Other',
  k1: 'K1 · rafters',
  battens: 'Battens',
  counterBattens: 'Counter battens',
  membrane: 'Membrane',
  tile: 'Roof tile',
  timberEvidence: 'Timber · geometric schedule',
  blankLength: 'Blank length',
  consumption: 'Declared manufacturer consumption',
  netArea: 'Net area',
  grossArea: 'Including overlaps',
  rollCount: 'Roll plan (current layout)',
  overlapArea: 'Laps between courses',
  endOverlapArea: 'Laps at roll joins',
  ridgeOverrunArea: 'Last course overrun at ridge',
  simplificationArea: 'Layout simplifications (eave width, openings)',
  courseCount: 'Membrane courses',
  course: 'courses',
  roll: 'rolls',
  membraneRollPlan: 'CONSERVATIVE PLAN',
  membraneNetOnly: 'NET ONLY',
  membraneRollPlanHelp:
    'Full courses from eave to ridge with the product overlap. Rolls are counted without re-laying leftover pieces — an upper estimate, not an exact purchase plan.',
  membraneNetOnlyHelp:
    'Roof geometry only. Choose a roll product to calculate overlaps, courses and rolls.',
  netHero: 'Net area',
  grossHero: 'Including overlaps',
  rollsHero: 'Plan for current layout',
  rollSize: 'Roll',
  rollWidth: 'Roll width',
  rollLength: 'Roll length',
  overlapUsed: 'Overlap (used)',
  manualData: 'MANUAL',
  manualDataHelp:
    'Technical data entered by the user — not from a catalogue revision.',
  catalogRevision: 'revision',
  noProduct: 'No product selected',
  limitations: 'What RoofCalc does not model yet',
  whyMore: 'Why more than net?',
  retry: 'Retry',
  geometryCount: 'Geometry',
  procurement: 'PURCHASE PLAN',
  fabrication: 'FABRICATION REQUIREMENT',
  geometry: 'GEOMETRY',
  manufacturer: 'MANUFACTURER ESTIMATE',
  partial: 'PARTIAL',
  catalogue: 'CATALOGUE',
  manual: 'MANUAL PRICE',
  noPrice: 'No price in list',
  selectPrice: 'Select price source',
  manualPrice: 'Manual net unit price',
  price: 'Net unit price',
  value: 'Net value',
  net: 'net',
  gross: 'source gross',
  verify: 'Verify price before purchase',
  commercial: 'Selected commercial material',
  online: 'Catalogue available',
  offline: 'Catalogue unavailable — you can work manually',
  loading: 'Checking catalogue…',
  cutting: 'K1 cutting plan',
  technical: 'Technical schedule',
  chooseTimber: 'Choose timber in K1 cutting plan',
  chooseMembrane: 'Change product',
  parameters: 'Parameters / manual entry',
  chooseCovering: 'Choose variant in Covering',
  details: 'Details and quantity basis',
  add: 'Add to estimate',
  update: 'Update estimate',
  keep: 'Keep current',
  review: 'Proposed update',
  manualOwned:
    'Manual quantity remains unchanged. Accept price updates explicitly.',
  rangeNote: 'Estimate — not a purchase quantity. No automatic allowance.',
  rangeCost: 'Cost range',
  rangeAction: 'Set quantity in estimate',
  count: 'Rows',
  purchaseCount: 'Purchase plan',
  estimates: 'Estimates',
  needsData: 'Need data',
  known: 'Known prices value (net)',
  incomplete: 'Partial value — excludes incomplete rows and missing prices.',
  csv: 'Download material CSV',
  export: 'Material list / print',
  empty: 'No materials yet. Complete structure, layers or covering.',
  'k1-needs-cutting':
    'Run a complete cutting plan to choose commercial lengths. This is a fabrication requirement.',
  'layer-not-resolved':
    'Quantity is unresolved. Review parameters and limitations in Layers.',
  'k1-execution-unresolved':
    'Axis geometry does not define blanks. K1 fabrication is unresolved for this configuration.',
  'no-allowance-no-stock-length': 'Without allowances or commercial cutting.',
  'partial-counter-battens':
    'Partial: K1/J1 axes and opening interruptions; H1 boundary detail remains unresolved.',
  'batten-gauge-unverified':
    'Manual gauge not verified against a covering — preliminary geometric length.',
  'batten-gauge-incompatible':
    'The batten gauge does not match the covering — geometric length needs correction.',
  'gross-area-no-roll-reuse':
    'Leftover roll pieces are not re-laid between courses.',
  'hip-course-width-approximated':
    'Hip planes are currently counted conservatively: every course uses the eave width.',
  'openings-not-subtracted':
    'Roof openings do not reduce the membrane requirement yet.',
  'membrane-sold-per-roll':
    'Sold per roll, but the estimate does not support a per-roll price yet — cost uses m² including overlaps.',
  'net-area-no-overlap-no-rolls':
    'Net geometric area without overlaps or rolls. Select a roll product.',
  'declared-consumption-not-a-resolved-purchase-count':
    'Manufacturer consumption estimate; not a purchase quantity.',
  'covering-not-a-purchase-count':
    'Coverage positions and geometric runs do not define purchase quantities.',
};
export function materialCopy(locale: string) {
  return locale.startsWith('pl') ? pl : en;
}
export function materialText(locale: string, key: string) {
  const copy = materialCopy(locale);
  return copy[key as keyof typeof copy] ?? key;
}
