/**
 * V52 copy for the "System dachu" workspace and its editors. Polish first;
 * English mirrors every key. No developer terminology in user text.
 */
function plural(n: number, one: string, few: string, many: string) {
  if (n === 1) return one;
  const tens = n % 100;
  return n % 10 >= 2 && n % 10 <= 4 && (tens < 12 || tens > 14) ? few : many;
}

const pl = {
  title: 'System dachu',
  intro:
    'Jeden model dachu → elementy systemowe → ilości do zakupu. Kliknij obszar, aby go uzupełnić.',
  counts: (ready: number, attention: number, optional: number) =>
    [
      `${ready} ${plural(ready, 'gotowy', 'gotowe', 'gotowych')}`,
      attention
        ? `${attention} ${plural(attention, 'wymaga', 'wymagają', 'wymaga')} decyzji`
        : '',
      optional
        ? `${optional} ${plural(optional, 'opcjonalny', 'opcjonalne', 'opcjonalnych')}`
        : '',
    ]
      .filter(Boolean)
      .join(' · '),
  complete: 'Uzupełnij system dachu',
  completeTitle: 'Czego jeszcze brakuje',
  completeHelp:
    'Lista pokazuje obszary tego dachu. Nic nie jest dodawane automatycznie — wybierasz sam.',
  close: 'Zamknij',
  attentionCount: (n: number) =>
    `${n} ${plural(n, 'rzecz wymaga', 'rzeczy wymagają', 'rzeczy wymaga')} decyzji`,
  fillMissing: 'Uzupełnij brakujące',
  detectedLength: 'Długość na dachu',
  needFor: (m: string) => `Potrzeba ${m}`,
  toBuy: 'Do zakupu',
  stepWindow: '1. Określ okno',
  stepCovering: '2. Potwierdź rodzaj pokrycia',
  stepFlashing: '3. Dobierz kołnierz',
  flashingNeeded: 'wymaga kołnierza',
  back: '← Wszystkie obszary',
  area: {
    covering: 'Pokrycie',
    ridge: 'Kalenica / grzbiety',
    verge: 'Skraje',
    eave: 'Okap',
    openings: 'Otwory',
    drainage: 'Odwodnienie',
  },
  state: {
    ready: '✓ Gotowe',
    'needs-decision': '⚠ Wymaga decyzji',
    'not-configured': '○ Opcjonalne',
    'not-applicable': 'Nie dotyczy',
  },
  item: {
    'base-covering': 'Pokrycie podstawowe',
    'tile-plan': 'Plan zakupu dachówki',
    'ridge-tiles': 'Gąsiory',
    'ridge-tape': 'Taśma kalenicowa',
    'ridge-end': 'Zakończenia kalenicy / grzbietów',
    'ridge-clip': 'Klamry gąsiorów',
    'verge-tiles': 'Dachówki skrajne',
    'verge-flashing': 'Obróbka skrajna',
    'eave-elements': 'Elementy okapu',
    'opening-flashing': (n?: number) => `Kołnierz · Okno ${n ?? ''}`.trim(),
    drainage: 'Odwodnienie',
  },
  layers: 'Warstwy rysunku',
  layer: {
    covering: 'Pokrycie',
    ridge: 'Kalenica',
    eave: 'Okap',
    drainage: 'Odwodnienie',
    openings: 'Otwory',
  },
  appliesTo: 'Dotyczy',
  showOnRoof: 'Pokaż na dachu',
  openCovering: 'Otwórz pokrycie',
  openTilePlan: 'Plan zakupu dachówki',
  openDrainage: 'Otwórz odwodnienie',
  tileAccessories:
    'Gąsiory i dachówki skrajne wybierasz w planie zakupu dachówki — tu widzisz ich wynik.',
  noCovering: 'Najpierw wybierz pokrycie dachu.',
  noTilePlan: 'Plan zakupu dachówki nie jest przygotowany.',
  add: '+ Dodaj element',
  addFromCatalogue: 'Z katalogu',
  addManual: 'Ręcznie',
  catalogueOffline: 'Katalog niedostępny — dodaj element ręcznie.',
  catalogueEmpty: 'Brak elementów w katalogu dla tego obszaru.',
  compatible: 'KOMPATYBILNE',
  systemElement: 'Element systemowy producenta',
  universal: 'Uniwersalny',
  incompatible: 'Niezgodne z wybranym pokryciem',
  catalog: 'KATALOG',
  manual: 'RĘCZNIE',
  producer: 'Producent',
  technicalData: 'Dane techniczne: producent',
  roll: (m: string) => `Rolka ${m}`,
  pieceCover: (cm: string) => `Krycie sztuki ${cm}`,
  ruleUnknown: 'Producent nie podaje zasady ilości',
  addThis: 'Dodaj',
  adding: 'Dodawanie…',
  confirmRule: 'Potwierdź zasadę ilości',
  confirmEnds: (n: number) =>
    `1 szt. na każdy otwarty koniec kalenicy / grzbietu (${n})`,
  confirmPerTile: '1 szt. na każdy gąsior',
  orManual: 'albo wpisz ilość ręcznie',
  role: 'Element',
  name: 'Nazwa produktu',
  rule: 'Jak liczyć',
  ruleOption: {
    'roll-length': 'W rolkach (długość rolki)',
    'linear-effective-cover': 'W sztukach (krycie jednej sztuki)',
    'one-per-feature-end': '1 na otwarty koniec',
    'one-per-ridge-tile': '1 na gąsior',
    manual: 'Ilość ręcznie',
    'one-per-joint': '',
    'one-per-course': '',
    'spacing-along-feature': '',
    'one-per-opening': '',
  } as Record<string, string>,
  rollLength: 'Długość rolki (m)',
  cover: 'Krycie jednej sztuki (cm)',
  quantity: 'Ilość (szt.)',
  allowance: 'Naddatek (m) — tylko jeśli chcesz',
  allowanceHelp: 'RoofCalc nie dodaje ukrytego procentu.',
  save: 'Dodaj',
  cancel: 'Anuluj',
  remove: 'Usuń',
  invalid: 'Uzupełnij nazwę i wartość dla wybranej zasady.',
  requirement: 'Wymaganie',
  purchase: 'Do zakupu',
  surplus: 'Nadwyżka handlowa',
  rolls: (n: number) => `${n} ${plural(n, 'rolka', 'rolki', 'rolek')}`,
  pieces: (n: number) => `${n} szt.`,
  needsDecision: 'Wymaga decyzji',
  openEnds: (n: number) =>
    `${n} ${plural(n, 'otwarty koniec', 'otwarte końce', 'otwartych końców')}`,
  openEndsLabel: 'Otwarte końce',
  eavesFor: 'Okapy z tym elementem',
  noComponents: 'Brak elementów.',
  verges: 'Skraje dachu',
  openingList: 'Okna dachowe',
  opening: (n: number) => `Okno ${n}`,
  plane: 'Połać',
  pitch: 'Kąt połaci',
  window: 'Okno',
  windowGeneric: 'Otwór ogólny — bez produktu',
  chooseWindow: 'Przypisz okno (opcjonalnie)',
  windowHelp:
    'Geometria działa bez produktu. Kołnierz systemowy wymaga wskazania okna.',
  coveringClass: 'Pokrycie przy oknie',
  coveringClassHelp:
    'Kołnierze są dobierane do rodzaju pokrycia. Potwierdź, co leży przy oknie.',
  profiled: 'Profilowane (dachówka, blachodachówka)',
  flat: 'Płaskie (łupek, gont)',
  flashing: 'Kołnierz',
  flashingRequired: 'Wymaga wyboru',
  notCompatible: 'NIEZGODNE — nie wliczono do materiałów',
  chooseFlashing: 'Dobierz kołnierz',
  kitIncludes: 'W zestawie',
  includes: {
    'window-flashing': 'kołnierz',
    'membrane-collar': 'kołnierz paroprzepuszczalny',
    'insulation-collar': 'rama izolacyjna',
  } as Record<string, string>,
  manualFlashing: 'Kołnierz ręcznie',
  manualFlashingName: 'Nazwa kołnierza',
  removeFlashing: 'Usuń kołnierz',
  sizeDiffers:
    'Rozmiar okna różni się od narysowanego otworu — sprawdź wymiary otworu.',
  drainageOff: 'Rynny nie są skonfigurowane (opcjonalne).',
  run: (n: number) => `Rynna R${n}`,
  eaveLength: 'Długość okapu',
  gutterPlan: 'Rynna',
  connectors: 'Łączniki',
  hooks: 'Haki',
  outlets: 'Odpływy',
  showHooks: 'Pokaż rozmieszczenie',
  hideHooks: 'Ukryj rozmieszczenie',
  hookSource: 'Źródło: max rozstaw haków i „nie na łączeniu” — producent.',
  hookStrategy: (cm: string) =>
    `Strategia RoofCalc: hak min. ${cm} od łącznika, równe odstępy.`,
  selectOnDrawing: 'Kliknij linię na rysunku, aby zobaczyć, czego dotyczy.',
  featureElements: 'Elementy na tej linii',
  none: '—',
};

type Copy = typeof pl;

const en: Copy = {
  ...pl,
  title: 'Roof system',
  intro:
    'One roof model → system elements → purchase quantities. Click an area to complete it.',
  counts: (ready, attention, optional) =>
    [
      `${ready} ready`,
      attention ? `${attention} need a decision` : '',
      optional ? `${optional} optional` : '',
    ]
      .filter(Boolean)
      .join(' · '),
  complete: 'Complete the roof system',
  completeTitle: 'What is still missing',
  completeHelp:
    'The list shows the areas of this roof. Nothing is added automatically — you choose.',
  close: 'Close',
  attentionCount: (n) =>
    `${n} ${n === 1 ? 'item needs' : 'items need'} a decision`,
  fillMissing: 'Complete missing',
  detectedLength: 'Length on the roof',
  needFor: (m) => `Needed ${m}`,
  toBuy: 'To buy',
  stepWindow: '1. Identify the window',
  stepCovering: '2. Confirm the covering type',
  stepFlashing: '3. Choose the flashing',
  flashingNeeded: 'needs a flashing',
  back: '← All areas',
  area: {
    covering: 'Covering',
    ridge: 'Ridge / hips',
    verge: 'Verges',
    eave: 'Eave',
    openings: 'Openings',
    drainage: 'Drainage',
  },
  state: {
    ready: '✓ Ready',
    'needs-decision': '⚠ Needs a decision',
    'not-configured': '○ Optional',
    'not-applicable': 'Not applicable',
  },
  item: {
    'base-covering': 'Base covering',
    'tile-plan': 'Tile purchase plan',
    'ridge-tiles': 'Ridge tiles',
    'ridge-tape': 'Ridge tape',
    'ridge-end': 'Ridge / hip ends',
    'ridge-clip': 'Ridge tile clips',
    'verge-tiles': 'Verge tiles',
    'verge-flashing': 'Verge flashing',
    'eave-elements': 'Eave elements',
    'opening-flashing': (n?: number) => `Flashing · Window ${n ?? ''}`.trim(),
    drainage: 'Drainage',
  },
  layers: 'Drawing layers',
  layer: {
    covering: 'Covering',
    ridge: 'Ridge',
    eave: 'Eave',
    drainage: 'Drainage',
    openings: 'Openings',
  },
  appliesTo: 'Applies to',
  showOnRoof: 'Show on roof',
  openCovering: 'Open covering',
  openTilePlan: 'Tile purchase plan',
  openDrainage: 'Open drainage',
  tileAccessories:
    'Ridge and verge tiles are chosen in the tile purchase plan — their result is shown here.',
  noCovering: 'Choose a roof covering first.',
  noTilePlan: 'The tile purchase plan is not prepared.',
  add: '+ Add element',
  addFromCatalogue: 'From the catalogue',
  addManual: 'Manually',
  catalogueOffline: 'Catalogue unavailable — add the element manually.',
  catalogueEmpty: 'No catalogue elements for this area.',
  compatible: 'COMPATIBLE',
  systemElement: 'Manufacturer system element',
  universal: 'Universal',
  incompatible: 'Not compatible with the chosen covering',
  catalog: 'CATALOGUE',
  manual: 'MANUAL',
  producer: 'Manufacturer',
  technicalData: 'Technical data: manufacturer',
  roll: (m) => `Roll ${m}`,
  pieceCover: (cm) => `Piece cover ${cm}`,
  ruleUnknown: 'The manufacturer states no quantity rule',
  addThis: 'Add',
  adding: 'Adding…',
  confirmRule: 'Confirm the quantity rule',
  confirmEnds: (n) => `1 per open ridge / hip end (${n})`,
  confirmPerTile: '1 per ridge tile',
  orManual: 'or enter a quantity',
  role: 'Element',
  name: 'Product name',
  rule: 'How to count',
  ruleOption: {
    ...pl.ruleOption,
    'roll-length': 'In rolls (roll length)',
    'linear-effective-cover': 'In pieces (cover of one piece)',
    'one-per-feature-end': '1 per open end',
    'one-per-ridge-tile': '1 per ridge tile',
    manual: 'Manual quantity',
  },
  rollLength: 'Roll length (m)',
  cover: 'Cover of one piece (cm)',
  quantity: 'Quantity (pcs)',
  allowance: 'Allowance (m) — only if you want one',
  allowanceHelp: 'RoofCalc adds no hidden percentage.',
  save: 'Add',
  cancel: 'Cancel',
  remove: 'Remove',
  invalid: 'Enter a name and the value for the chosen rule.',
  requirement: 'Requirement',
  purchase: 'To buy',
  surplus: 'Commercial surplus',
  rolls: (n) => `${n} ${n === 1 ? 'roll' : 'rolls'}`,
  pieces: (n) => `${n} pcs`,
  needsDecision: 'Needs a decision',
  openEnds: (n) => `${n} open ${n === 1 ? 'end' : 'ends'}`,
  openEndsLabel: 'Open ends',
  eavesFor: 'Eaves with this element',
  noComponents: 'No elements.',
  verges: 'Roof verges',
  openingList: 'Roof windows',
  opening: (n) => `Window ${n}`,
  plane: 'Plane',
  pitch: 'Pitch',
  window: 'Window',
  windowGeneric: 'Generic opening — no product',
  chooseWindow: 'Assign a window (optional)',
  windowHelp:
    'Geometry works without a product. A system flashing needs the window.',
  coveringClass: 'Covering at the window',
  coveringClassHelp:
    'Flashings are matched to the covering type. Confirm what lies at the window.',
  profiled: 'Profiled (tiles, metal tiles)',
  flat: 'Flat (slate, shingles)',
  flashing: 'Flashing',
  flashingRequired: 'Needs a choice',
  notCompatible: 'INCOMPATIBLE — not counted in materials',
  chooseFlashing: 'Choose a flashing',
  kitIncludes: 'Included',
  includes: {
    'window-flashing': 'flashing',
    'membrane-collar': 'membrane collar',
    'insulation-collar': 'insulation frame',
  },
  manualFlashing: 'Manual flashing',
  manualFlashingName: 'Flashing name',
  removeFlashing: 'Remove flashing',
  sizeDiffers:
    'The window size differs from the drawn opening — check the opening size.',
  drainageOff: 'Gutters are not configured (optional).',
  run: (n) => `Gutter R${n}`,
  eaveLength: 'Eave length',
  gutterPlan: 'Gutter',
  connectors: 'Connectors',
  hooks: 'Hooks',
  outlets: 'Outlets',
  showHooks: 'Show placement',
  hideHooks: 'Hide placement',
  hookSource: 'Source: max hook spacing and “not at a joint” — manufacturer.',
  hookStrategy: (cm) =>
    `RoofCalc strategy: hooks at least ${cm} from a connector, even spacing.`,
  selectOnDrawing: 'Click a line on the drawing to see what applies to it.',
  featureElements: 'Elements on this line',
};

export type RoofSystemCopy = Copy;
export const roofSystemCopy = (locale: string): Copy =>
  locale.startsWith('pl') ? pl : en;
